import React from "react";

const Privacy = () => {
  return (
    <div style={{ padding: "20px", maxWidth: "800px", margin: "0 auto" }} className="container mx-auto p-4">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="text-gray-600">Last updated: February 13, 2025</p>
      <p className="mt-4">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information
        when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p className="mt-4">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and
        use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the
        <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer" className="text-blue-600"> Privacy Policy Generator</a>.
      </p>
      
      <h2 className="text-2xl font-semibold mt-6">Interpretation and Definitions</h2>
      <h3 className="text-xl font-semibold mt-4">Interpretation</h3>
      <p className="mt-2">
        The words of which the initial letter is capitalized have meanings defined under the following conditions.
        The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>
      
      <h3 className="text-xl font-semibold mt-4">Definitions</h3>
      <ul className="list-disc ml-6 mt-2">
        <li><strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate:</strong> An entity that controls, is controlled by, or is under common control with a party.</li>
        <li><strong>Application:</strong> Refers to Human Chat, the software program provided by the Company.</li>
        <li><strong>Company:</strong> ("We", "Us", "Our") refers to Human Chat.</li>
        <li><strong>Country:</strong> Refers to Brazil.</li>
        <li><strong>Device:</strong> Any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</li>
        <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service:</strong> Refers to the Application.</li>
        <li><strong>Service Provider:</strong> Any natural or legal person who processes the data on behalf of the Company.</li>
        <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><strong>You:</strong> The individual accessing or using the Service, or a legal entity on behalf of which such individual is accessing the Service.</li>
      </ul>
      
      <h2 className="text-2xl font-semibold mt-6">Collecting and Using Your Personal Data</h2>
      <h3 className="text-xl font-semibold mt-4">Types of Data Collected</h3>
      <h4 className="text-lg font-semibold mt-3">Personal Data</h4>
      <p className="mt-2">
        While using Our Service, We may ask You to provide Us with certain personally identifiable information, including but not limited to:
      </p>
      <ul className="list-disc ml-6 mt-2">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>
      
      <h4 className="text-lg font-semibold mt-3">Usage Data</h4>
      <p className="mt-2">
        Usage Data is collected automatically when using the Service and may include information such as Your Device’s IP address,
        browser type, browser version, pages visited, time spent on pages, unique device identifiers, and other diagnostic data.
      </p>
      
      <h3 className="text-xl font-semibold mt-4">Use of Your Personal Data</h3>
      <p className="mt-2">The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc ml-6 mt-2">
        <li>To provide and maintain our Service, including monitoring usage.</li>
        <li>To manage Your Account as a registered user.</li>
        <li>For the performance of a contract, including purchases and service agreements.</li>
        <li>To contact You via email, phone, SMS, or push notifications.</li>
        <li>To provide You with relevant news, special offers, and promotions.</li>
        <li>To manage Your requests and improve our services.</li>
      </ul>
      
      <h3 className="text-xl font-semibold mt-4">Security of Your Personal Data</h3>
      <p className="mt-2">
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure.
      </p>
      
      <h2 className="text-2xl font-semibold mt-6">Children's Privacy</h2>
      <p className="mt-2">
        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13.
      </p>
      
      <h2 className="text-2xl font-semibold mt-6">Changes to This Privacy Policy</h2>
      <p className="mt-2">
        We may update Our Privacy Policy from time to time. You are advised to review this Privacy Policy periodically for any changes.
      </p>
    </div>
  );
};

export default Privacy;
